name             'laravel'
maintainer       'Sergiu Ionescu'
maintainer_email 'sergiu.ionescu@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures laravel'
long_description 'Installs/Configures laravel'
version          '0.1.0'

depends 'php'
depends 'lamp'
depends 'cron'
depends 'composer'
depends 'git'